### ISSUE TITLE
Members Grid — Broken design on mobile

### ISSUE THREAD

**Issue by nilbuild** [kamranahmedse/makers.ae#2]
"Become a Member"  on homepage is broken for smaller devices.

![image](https://user-images.githubusercontent.com/4921183/97900417-05ff2e00-1d54-11eb-9bd9-bd20ba64bf65.png)

Let's change the text to "Join now" on smaller devices

**Comment by abidhkm** [comment]
taking this issue

**Comment by AdnanLatif** [comment]
Issue resolved working when saw this issue and sorry for not telling there that I am working on it.
Please pull new branch and check everything working fine or need some more changes.
Thanks.
**Mobile Preview**
![image](https://user-images.githubusercontent.com/2950599/97917558-7454e800-1d76-11eb-9216-9124303b3c36.png)
**Desktop Preview**
![image](https://user-images.githubusercontent.com/2950599/97917663-9f3f3c00-1d76-11eb-9c6f-de75372837e7.png)

**Comment by tauqeernasir** [comment]
https://github.com/kamranahmedse/makers.ae/pull/7
