### ISSUE TITLE
Add the profile page

### ISSUE THREAD

**Issue by nilbuild** [kamranahmedse/makers.ae#4]
We need to add a new page for the profile, so whenever a member is clicked, we will load more details.

I have [partially added the UI](https://makers.ae/profile), just need to add a dynamic route that will take the username, load the [profile from the JSON file](https://github.com/kamranahmedse/makers.ae/blob/master/data/members/kamran/profile.json) and load the [bio from the bio file](https://github.com/kamranahmedse/makers.ae/blob/master/data/members/kamran/bio.md). 

For the markdown, we can use [remark](https://github.com/remarkjs/remark) along with [remark-html](https://github.com/remarkjs/remark-html). Here is a [sample usage for that](https://github.com/vercel/next.js/blob/a529e6736f42af7a458f0e350a49fba97ec8f52a/examples/blog-starter/lib/markdownToHtml.js#L4).

**Comment by HanyRabah** [comment]
Working on this issue

**Comment by AdnanLatif** [comment]
Sure. Go ahead. I was working on it but I am kind a new to react and next.
I need some more learning specially nextjs.

--
Thanks & Regards
Adnan Latif
Software Engineer
Cell  #  +92-321-6850321
Skype: adnanlatif.bwp
