### ISSUE TITLE
Add a command to add new member

### ISSUE THREAD

**Issue by nilbuild** [kamranahmedse/makers.ae#6]
The command signature should be:

```shell
yarn cmd members.add
```

After you run the command, it should ask you for [all the profile fields](https://github.com/kamranahmedse/makers.ae/blob/master/data/members/kamran/profile.json), including the image URL. Allow the user to add any remote image URL. Once the user has given all the fields:

* Download the image from the remote URL and place it in the [public/avatars directory](https://github.com/kamranahmedse/makers.ae/tree/master/public/avatars). 
* Create a directory with username in `data/members/{username}`
* Create `profile.json` with all the required fields in `data/members/{username}/profile.json`
* Create empty `bio.md` file in `data/members/{username}`

Also, make sure to add validation to all the fields.

We can use [inquirer.js](https://github.com/SBoudrias/Inquirer.js) for the inputs.

**Comment by abidhkm** [comment]
I would like to try this, will take if nobody has started

**Comment by AdnanLatif** [comment]
Take it. It all yours.

--
Thanks & Regards
Adnan Latif
Software Engineer
Cell  #  +92-321-6850321
Skype: adnanlatif.bwp

**Comment by abidhkm** [comment]
PR for this issue - https://github.com/kamranahmedse/makers.ae/pull/8
